Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -39,6 +39,7 @@ jobs:
                 timestamp=$(git log -1 --format=%ai -- "$file" | cut -d ' ' -f 1,2 | tr ' ' 'T')Z
                 contributors=$(git log -1 --format='%an <%ae>' -- "$file")
 
+                tmp_file=$(mktemp)
                 jq --arg name "$setting_id" \
                    --arg data "$data" \
                    --arg checksum "$checksum" \
@@ -50,7 +51,7 @@ jobs:
                      "checksum": $checksum,
                      "timestamp": $timestamp,
                      "contributors": $contributors
-                   }]' "${safe_branch_name}-settings.json" > temp.json && mv temp.json "${safe_branch_name}-settings.json"
+                   }]' "${safe_branch_name}-settings.json" > "$tmp_file" && mv "$tmp_file" "${safe_branch_name}-settings.json"
               fi
             done
           }
@@ -62,22 +63,13 @@ jobs:
           
             if [ -s "$settings_file" ]; then
               echo "Uploading settings for branch: $branch"
-              response=$(curl -s -w "%{http_code}" -o /tmp/curl_output \
-                -X POST \
+              curl --fail -X POST \
                 -H "Authorization: $AUTHORIZATION" \
                 -H "Content-Type: application/json" \
                 -d @"$settings_file" \
-                "https://api-testing.liquidbounce.net/api/v1/client/$branch/settings/sync")
-          
-              if [ "$response" -eq 200 ] || [ "$response" -eq 204 ]; then
-                echo "Settings successfully uploaded for branch: $branch"
-              else
-                echo "Failed to upload settings for branch: $branch"
-                echo "HTTP Status Code: $response"
-                echo "Response Body:"
-                cat /tmp/curl_output
-                exit 1
-              fi
+                "https://api-testing.liquidbounce.net/api/v1/client/$branch/settings/sync" \
+                && echo "Settings successfully uploaded for branch: $branch" \
+                || (echo "Failed to upload settings for branch: $branch" && exit 1)
             else
               echo "No settings to upload for branch: $branch"
             fi
